// Generated by `BiomeScanner --calibrate`; do not edit by hand. Rerun it after changing climate
// biomes or their targets, the climate noise, or the climate cells.

#pragma once

#include <array>
#include <utility>

inline constexpr std::array<std::pair<const char*, float>, 12> calibratedClimateBiases{ {
    { "plains", -0.01996f },
    { "desert", 0.02020f },
    { "forest", 0.01696f },
    { "tundra", -0.08281f },
    { "savanna", 0.05877f },
    { "ice fields", -0.07875f },
    { "flower meadow", 0.04212f },
    { "old-growth forest", 0.02767f },
    { "cherry grove", 0.05878f },
    { "taiga", -0.07639f },
    { "birch forest", -0.03121f },
    { "redwood forest", 0.06461f },
} };
