# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Aditya Gupta
"""Generates ggx_fresnel_tables.hlsli: the average dielectric Fresnel reflectance over the GGX
distribution of visible normals, E_F(wo) = integral of F(wo.h) D_wo(h) dh, for glossy reflection
layered over a diffuse lobe with per-microfacet Fresnel. Run with numpy; writes next to this file.

Each half of the table is indexed [z][cosThetaV][roughness] with z = sqrt((ior - 1) / (ior + 1)),
covering z up to MAX_Z; the second half is for relative ior below 1, looked up with 1/ior, and
measures its angle axis from the critical angle (ggxCriticalCosAxis in ggx.hlsli) so the total
internal reflection ramp falls on the same coordinate in every z slice and interpolates cleanly.
"""
import os

import numpy as np

NUM_Z = 24
NUM_COS = 32
NUM_ROUGHNESS = 16
MAX_Z = 0.66  # ior ratio up to ~2.5
NUM_STRATA = 96  # per axis of the stratified VNDF quadrature


def fresnel(eta, c):
    """Unpolarized dielectric Fresnel, as walterFresnel in materials.hlsli."""
    c = np.maximum(c, 1e-7)  # eta = 1 at c = 0 would divide 0 by 0
    g2 = eta * eta - 1.0 + c * c
    tir = g2 < 0.0
    g = np.sqrt(np.maximum(g2, 0.0))
    a = (g - c) / (g + c)
    b = (c * (g + c) - 1.0) / (c * (g - c) + 1.0)
    return np.where(tir, 1.0, 0.5 * a * a * (1.0 + b * b))


def critical_cos(eta):
    return np.sqrt(max(1.0 - eta * eta, 0.0))


def critical_cos_axis_inverse(x, cos_c):
    """The cosThetaV at coordinate x of ggxCriticalCosAxis."""
    return 2.0 * x * cos_c if x < 0.5 else cos_c + (2.0 * x - 1.0) * (1.0 - cos_c)


def vndf_cos_wo_h(cos_v, alpha, u1, u2):
    """wo.h for VNDF samples (Heitz 2018) with wo in the xz plane."""
    wo = np.array([np.sqrt(max(1.0 - cos_v * cos_v, 0.0)), 0.0, cos_v])
    vh = np.array([alpha * wo[0], alpha * wo[1], wo[2]])
    vh /= np.linalg.norm(vh)
    len_sq = vh[0] ** 2 + vh[1] ** 2
    t1 = np.array([-vh[1], vh[0], 0.0]) / np.sqrt(len_sq) if len_sq > 0.0 else np.array([1.0, 0.0, 0.0])
    t2 = np.cross(vh, t1)
    r = np.sqrt(u1)
    phi = 2.0 * np.pi * u2
    p1 = r * np.cos(phi)
    p2 = r * np.sin(phi)
    s = 0.5 * (1.0 + vh[2])
    p2 = (1.0 - s) * np.sqrt(np.maximum(1.0 - p1 * p1, 0.0)) + s * p2
    p3 = np.sqrt(np.maximum(1.0 - p1 * p1 - p2 * p2, 0.0))
    nh = p1[:, None] * t1 + p2[:, None] * t2 + p3[:, None] * vh
    h = np.stack([alpha * nh[:, 0], alpha * nh[:, 1], np.maximum(nh[:, 2], 0.0)], axis=1)
    h /= np.linalg.norm(h, axis=1, keepdims=True)
    return np.clip(h @ wo, 0.0, 1.0)


def table(inverse):
    strata = (np.arange(NUM_STRATA) + 0.5) / NUM_STRATA
    u1, u2 = (a.ravel() for a in np.meshgrid(strata, strata))
    out = np.zeros((NUM_Z, NUM_COS, NUM_ROUGHNESS))
    for zi in range(NUM_Z):
        z = MAX_Z * zi / (NUM_Z - 1)
        ior = (1.0 + z * z) / (1.0 - z * z)
        eta = 1.0 / ior if inverse else ior
        cos_c = critical_cos(eta) if inverse else 0.0
        for ci in range(NUM_COS):
            x = ci / (NUM_COS - 1)
            cos_v = max(critical_cos_axis_inverse(x, cos_c) if inverse else x, 1e-4)
            for ri in range(NUM_ROUGHNESS):
                alpha = max((ri / (NUM_ROUGHNESS - 1)) ** 2, 1e-4)
                out[zi, ci, ri] = fresnel(eta, vndf_cos_wo_h(cos_v, alpha, u1, u2)).mean()
    return out


if __name__ == '__main__':
    values = np.concatenate([table(False).ravel(), table(True).ravel()])
    rows = ',\n'.join('    ' + ', '.join(f'{v:.6f}f' for v in row) for row in values.reshape(-1, NUM_ROUGHNESS))
    text = f'''// SPDX-License-Identifier: MIT
// Copyright (c) 2025-2026 Aditya Gupta
// Generated by gen_ggx_fresnel_tables.py; do not edit by hand.

#pragma once

// Average dielectric Fresnel reflectance over the GGX visible normals seen from wo: the share of light a
// glossy reflection lobe with per-microfacet Fresnel reflects, leaving the rest to the lobe beneath it.
// Two halves indexed [z][cosThetaV][roughness] with z = sqrt((ior - 1) / (ior + 1)) / GGX_FRESNEL_TABLE_MAX_Z;
// the second covers relative ior below 1, looked up with 1/ior and ggxCriticalCosAxis.

static const uint3 GGX_FRESNEL_TABLE_SIZE = uint3({NUM_ROUGHNESS}u, {NUM_COS}u, {NUM_Z}u); // roughness, cosThetaV, z
static const float GGX_FRESNEL_TABLE_MAX_Z = {MAX_Z}f;
static const uint GGX_FRESNEL_INV_TABLE_OFFSET = {NUM_Z * NUM_COS * NUM_ROUGHNESS}u;

static const float ggxFresnelETable[{values.size}] = {{
{rows}
}};
'''
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'ggx_fresnel_tables.hlsli')
    with open(path, 'w', newline='\r\n') as f:
        f.write(text)
    print(path)
