// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Aditya Gupta
#pragma once

// Shared host/shader protocol; keep buffer sizing and indices in one place.
enum SharcCounter
{
    SHARC_COUNTER_QUERIES,
    SHARC_COUNTER_HITS,
    SHARC_COUNTER_BOUNCES,
    SHARC_COUNTER_UPDATES,
    SHARC_COUNTER_FAILED_INSERTS,
    SHARC_COUNTER_OCCUPIED,
    SHARC_COUNTER_PRIMARY_RAYS,
    SHARC_COUNTER_PRIMARY_EMITTER_HITS,
    SHARC_COUNTER_PRIMARY_GLASS,
    SHARC_COUNTER_PRIMARY_GLASS_RAYS,
    SHARC_COUNTER_PRIMARY_GLASS_CACHE_HITS,
    SHARC_COUNTER_PRIMARY_GLASS_QUERIED,
    SHARC_COUNTER_TEST_VALUE_PASSED,
    SHARC_COUNTER_TEST_MISSES,
    SHARC_COUNTER_COUNT
};

enum SharcMaintenanceMode
{
    SHARC_MAINTENANCE_CLEAR,
    SHARC_MAINTENANCE_RESOLVE,
    SHARC_MAINTENANCE_TEST_INSERT,
    SHARC_MAINTENANCE_TEST_QUERY,
    SHARC_MAINTENANCE_TEST_MISS,
    SHARC_MAINTENANCE_RESET_STATS,
};
